#!/bin/sh
set -eu

if [ "$1" = configure ]; then
  if command -v apparmor_parser >/dev/null 2>&1 &&
     [ -d /sys/kernel/security/apparmor ]; then
    apparmor_parser -r /etc/apparmor.d/opt.git-desktop.desktop
  fi
  if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database /usr/share/applications
  fi
  if command -v gtk-update-icon-cache >/dev/null 2>&1; then
    gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor || true
  fi
fi
